### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by joshua-nilsson** [alxgiraud/fantasygen#3]
http://fantasygen.herokuapp.com/
@alxgiraud 

**Application error**
An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
`heroku logs --tail`

**Comment by alxgiraud** [comment]
Hi @joshua-nilsson, unfortunatly Heroku has become a pay service so the generator is no longer hosted. I'll have to look into it for a free alternative, but it's been a while since I got my hands into web development. Thanks for bringing it up, to be honest I didn't think this site was still visited after all these years 😅

**Comment by alxgiraud** [comment]
Fixed. Repo is now directly hosted on Github pages.
https://alxgiraud.github.io/fantasygen
